# use the minimal travis environment since we test in conda
language: minimal

os:
  - osx
  - linux

env:
  - global:
      - CC_TEST_REPORTER_ID=b24ce37bbd695b5180b567c60d494dad8c391b07241e62ebe31c24fe421671ae
      - PYTHON_VERSION: "3.6"

before_install:
  # install miniconda
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda -f
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda config --set always_yes yes

install:
  # python version is specified in environment.yml
  - conda env create -n genomepy python=$PYTHON_VERSION -f environment.yml
  - source activate genomepy
  - python setup.py develop
  - python setup.py build
#  - pip install coveralls

script:
  - black --check genomepy/ setup.py tests/
  - flake8 setup.py genomepy/ tests/
  - py.test -v
  - genomepy providers
#after_sucess:
#  coveralls
