dist:xenial
language: python

matrix:
  include:
    - os: osx
      language: generic
    - os: linux
      sudo: false
      dist: trusty
      language: python
      python: "2.7"
    - os: linux
      sudo: false
      dist: trusty
      language: python
      python: "3.5"
    - os: linux
      sudo: false
      dist: trusty
      language: python
      python: "3.6"

#cache:
#  apt: true
#  directories:
#    - $HOME/miniconda

before_install:
  # install miniconda for Python dependencies
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda -f
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda config --set always_yes yes
  - conda update --yes conda
  - conda config --add channels r
  - conda config --add channels defaults
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  - conda info -a

install:
  - conda install ucsc-genepredtobed ucsc-genepredtogtf ucsc-bedtogenepred ucsc-gtftogenepred bwa minimap2 bowtie2 hisat2 gmap pyfaidx>=0.5.1 bucketcache norns>0.1.1 xmltodict pytest coverage pyyaml requests
  - python setup.py develop
  - python setup.py build
  - pip install coveralls

# # command to run tests, e.g. python setup.py test
script:  
  - py.test -v
  - genomepy providers 
#after_sucess:
#  coveralls
