name: genomepy_travis
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.6.*
  - click
  - pyfaidx>=0.5.1
  - norns>=0.1.5
  - bucketcache
  - xmltodict
  - requests
  - biopython>=1.73
  - psutil
  - appdirs

  # Bgzip
  - tabix

  # Annotation downloading
  - ucsc-genepredtobed
  - ucsc-genepredtogtf
  - ucsc-bedtogenepred
  - ucsc-gff3togenepred
  - ucsc-gtftogenepred

  # Plugins
  - bwa
  - minimap2
  - bowtie2
  - hisat2
  - gmap

  # Distribution
  - setuptools
  - pypandoc

  # Testing
  - flake8
  - flake8-bugbear
  - black
  - pytest
