name: genomepy_travis
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.6.*
  - click
  - pyfaidx>=0.5.1
  - bucketcache
  - xmltodict
  - norns>0.1.5
#  - pyyaml
  - requests
#  - biopython
  - appdirs
  - ucsc-genepredtobed
  - ucsc-genepredtogtf
  - ucsc-bedtogenepred
  - ucsc-gff3togenepred
  - ucsc-gtftogenepred 
  - bwa
  - minimap2
  - bowtie2
  - hisat2
  - gmap
  - tabix
  - psutil
  
  # Testing etc.
#  - autopep8
  - flake8
  - flake8-bugbear
  - black
#  - coverage
  - pytest
  - pypandoc
