name: genomepy_travis
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.6.*
  - click
  - pyfaidx>=0.5.1
  - bucketcache
  - xmltodict
  - norns>=0.1.5
  - requests
  - biopython>=1.73
  - appdirs
  - ucsc-genepredtobed
  - ucsc-genepredtogtf
  - ucsc-bedtogenepred
  - ucsc-gff3togenepred
  - ucsc-gtftogenepred 
  - bwa
  - minimap2
  - bowtie2
  - hisat2
  - gmap
  - tabix
  - psutil
  - setuptools

  # Testing etc.
  - flake8
  - flake8-bugbear
  - black
  - pytest
  - pypandoc
